# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hm_arayüzü.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(246, 392)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 241, 91))
        self.label.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.pb_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_7.setGeometry(QtCore.QRect(0, 151, 61, 61))
        self.pb_7.setStyleSheet("QPushButton{\n"
" \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"     color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_7.setObjectName("pb_7")
        self.pb_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_8.setGeometry(QtCore.QRect(61, 151, 61, 61))
        self.pb_8.setStyleSheet("QPushButton{\n"
" \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"     color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_8.setObjectName("pb_8")
        self.pb_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_9.setGeometry(QtCore.QRect(122, 151, 61, 61))
        self.pb_9.setStyleSheet("QPushButton{\n"
" \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"     color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_9.setObjectName("pb_9")
        self.pb_carp = QtWidgets.QPushButton(self.centralwidget)
        self.pb_carp.setGeometry(QtCore.QRect(183, 151, 61, 61))
        self.pb_carp.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 158, 39);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 158, 39);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_carp.setObjectName("pb_carp")
        self.pb_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_4.setGeometry(QtCore.QRect(0, 210, 61, 61))
        self.pb_4.setStyleSheet("QPushButton{\n"
" \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"     color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_4.setObjectName("pb_4")
        self.pb_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_5.setGeometry(QtCore.QRect(61, 210, 61, 61))
        self.pb_5.setStyleSheet("QPushButton{\n"
" \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"     color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_5.setObjectName("pb_5")
        self.pb_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_6.setGeometry(QtCore.QRect(122, 210, 61, 61))
        self.pb_6.setStyleSheet("QPushButton{\n"
" \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"     color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_6.setObjectName("pb_6")
        self.pb_cikar = QtWidgets.QPushButton(self.centralwidget)
        self.pb_cikar.setGeometry(QtCore.QRect(183, 210, 61, 61))
        self.pb_cikar.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 158, 39);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 158, 39);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_cikar.setObjectName("pb_cikar")
        self.pb_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_1.setGeometry(QtCore.QRect(0, 270, 61, 61))
        self.pb_1.setStyleSheet("QPushButton{\n"
" \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"     color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_1.setObjectName("pb_1")
        self.pb_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_2.setGeometry(QtCore.QRect(61, 270, 61, 61))
        self.pb_2.setStyleSheet("QPushButton{\n"
" \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"     color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_2.setObjectName("pb_2")
        self.pb_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_3.setGeometry(QtCore.QRect(122, 270, 61, 61))
        self.pb_3.setStyleSheet("QPushButton{\n"
" \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"     color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_3.setObjectName("pb_3")
        self.pb_topla = QtWidgets.QPushButton(self.centralwidget)
        self.pb_topla.setGeometry(QtCore.QRect(183, 270, 61, 61))
        self.pb_topla.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 158, 39);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 158, 39);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_topla.setObjectName("pb_topla")
        self.pb_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_0.setGeometry(QtCore.QRect(0, 330, 121, 61))
        self.pb_0.setStyleSheet("QPushButton{\n"
" \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"     color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_0.setObjectName("pb_0")
        self.pb_nokta = QtWidgets.QPushButton(self.centralwidget)
        self.pb_nokta.setGeometry(QtCore.QRect(121, 330, 62, 61))
        self.pb_nokta.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 213, 106);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 213, 106);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_nokta.setObjectName("pb_nokta")
        self.pb_esit = QtWidgets.QPushButton(self.centralwidget)
        self.pb_esit.setGeometry(QtCore.QRect(183, 330, 61, 61))
        self.pb_esit.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 158, 39);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 158, 39);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_esit.setObjectName("pb_esit")
        self.pb_C = QtWidgets.QPushButton(self.centralwidget)
        self.pb_C.setGeometry(QtCore.QRect(0, 90, 61, 61))
        self.pb_C.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 213, 106);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 213, 106);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_C.setObjectName("pb_C")
        self.pb_isaret = QtWidgets.QPushButton(self.centralwidget)
        self.pb_isaret.setGeometry(QtCore.QRect(61, 90, 61, 61))
        self.pb_isaret.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 213, 106);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 213, 106);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_isaret.setObjectName("pb_isaret")
        self.pb_yuzde = QtWidgets.QPushButton(self.centralwidget)
        self.pb_yuzde.setGeometry(QtCore.QRect(122, 90, 61, 61))
        self.pb_yuzde.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 213, 106);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 213, 106);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_yuzde.setObjectName("pb_yuzde")
        self.pb_bol = QtWidgets.QPushButton(self.centralwidget)
        self.pb_bol.setGeometry(QtCore.QRect(183, 90, 61, 61))
        self.pb_bol.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 158, 39);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 158, 39);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pb_bol.setObjectName("pb_bol")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "0"))
        self.pb_7.setText(_translate("MainWindow", "7"))
        self.pb_8.setText(_translate("MainWindow", "8"))
        self.pb_9.setText(_translate("MainWindow", "9"))
        self.pb_carp.setText(_translate("MainWindow", "x"))
        self.pb_4.setText(_translate("MainWindow", "4"))
        self.pb_5.setText(_translate("MainWindow", "5"))
        self.pb_6.setText(_translate("MainWindow", "6"))
        self.pb_cikar.setText(_translate("MainWindow", "-"))
        self.pb_1.setText(_translate("MainWindow", "1"))
        self.pb_2.setText(_translate("MainWindow", "2"))
        self.pb_3.setText(_translate("MainWindow", "3"))
        self.pb_topla.setText(_translate("MainWindow", "+"))
        self.pb_0.setText(_translate("MainWindow", "0"))
        self.pb_nokta.setText(_translate("MainWindow", "."))
        self.pb_esit.setText(_translate("MainWindow", "="))
        self.pb_C.setText(_translate("MainWindow", "C"))
        self.pb_isaret.setText(_translate("MainWindow", "+/-"))
        self.pb_yuzde.setText(_translate("MainWindow", "%"))
        self.pb_bol.setText(_translate("MainWindow", "/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
